theme: minima
plugins:
  - jekyll-relative-links
  - jekyll-github-metadata
relative_links:
  enabled: true
  collections: true

title: "android-starter-v4"
description: "An Android template project (in Kotlin) with boilerplate and current patterns."
author: "by Matthias Urhahn"

include:
  - PRIVACY_POLICY.md
exclude:
  - buildSrc
  - gradle/wrapper
  - fastlane
  - Gemfile
  - Gemfile.lock
  - crowdin*
  - app